// Generated by https://quicktype.io

export interface MovieFullDetail {
    adult:                 boolean;
    backdrop_path:         string;
    belongs_to_collection: null;
    budget:                number;
    genres:                Genre[];
    homepage:              string;
    id:                    number;
    imdb_id:               string;
    original_language:     OriginalLanguage;
    original_title:        string;
    overview:              string;
    popularity:            number;
    poster_path:           string;
    production_companies:  ProductionCompany[];
    production_countries:  ProductionCountry[];
    release_date:          string;
    revenue:               number;
    runtime:               number;
    spoken_languages:      SpokenLanguage[];
    status:                string;
    tagline:               string;
    title:                 string;
    video:                 boolean;
    vote_average:          number;
    vote_count:            number;
    videos:                Videos;
    images:                Images;
}

export interface Genre {
    id:   number;
    name: string;
}

export interface Images {
    backdrops: Backdrop[];
    posters:   Backdrop[];
}

export interface Backdrop {
    aspect_ratio: number;
    file_path:    string;
    height:       number;
    iso_639_1:    null | string;
    vote_average: number;
    vote_count:   number;
    width:        number;
}

export enum OriginalLanguage {
    En = "en",
}

export interface ProductionCompany {
    id:             number;
    logo_path:      null | string;
    name:           string;
    origin_country: string;
}

export interface ProductionCountry {
    iso_3166_1: string;
    name:       string;
}

export interface SpokenLanguage {
    english_name: string;
    iso_639_1:    OriginalLanguage;
    name:         string;
}

export interface Videos {
    results: Result[];
}

export interface Result {
    id:         string;
    iso_639_1:  OriginalLanguage;
    iso_3166_1: ISO3166_1;
    key:        string;
    name:       string;
    site:       Site;
    size:       number;
    type:       Type;
}

export enum ISO3166_1 {
    Us = "US",
}

export enum Site {
    YouTube = "YouTube",
}

export enum Type {
    Featurette = "Featurette",
    Teaser = "Teaser",
    Trailer = "Trailer",
}
